### ISSUE TITLE
Compute vs storage

### ISSUE THREAD

**Issue by Suven** [versatiles-org/node-versatiles-server#2]
Hey!

I really like what you are doing with versatiles. Thank you so much for your efforts!

I was looking into ways to provide vector maps myself in the past for a commercial product and did similar stuff to you in the generation phase, but chose a different approach for serving them.

I figured S3-Storage would be cheaper (and faster) then running a server that serves the tiles and pregenerated all zoom levels (up to 13 I believe). The biggest downside is that updating takes a very long time. So I would not have daily dumps of OSM.

Did you have thoughts about this too? I'm just curious about your considerations.

Edit:/ Just to make sure.. By storage I mean storing the pbf-files as they are being consumed by maplibre-gl and co. My understanding is that shortbread is, itself, also an intermediate format. But maybe I am wrong about that?

**Comment by MichaelKreil** [comment]
If you want to use VersaTiles only with AWS S3, you can:
1. Extract all tiles to a folder (`versatiles convert --bbox ... --max-zoom ... "https://download.versatiles.org/osm.versatiles" ./folder/`) and synchronise them, but this could take a long time.
2. Alternatively, you can convert them to a `*.pmtiles` container (`versatiles convert ... "https://download.versatiles.org/osm.versatiles" osm.pmtiles`) and use the [Protomaps MapLibre Plugin](https://docs.protomaps.com/pmtiles/maplibre), but I think the latency of loading the map tiles might be an issue for you.

I would suggest a third option:
- Upload the `osm.versatiles` to AWS S3
- Use AWS Lambda with NodeJS and e.g. [@versatiles/server](https://www.npmjs.com/package/@versatiles/server) to serve the tiles from the bucket container to an AWS CDN.

We use a similar approach in Google Cloud and it works really well. Basically your only cost is the CDN traffic cost as Lambda is almost free.
But we haven't tested it in AWS yet. So we might have to tweak it a little bit, but I would be happy to help you with that... depending on your timeline ...
